# Generated by Django 4.1.3 on 2023-05-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.IntegerField(db_column='Branch_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('status_b', models.IntegerField(db_column='Status_b')),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
    ]
