# Generated by Django 4.1.3 on 2023-05-29 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': True},
        ),
    ]
