# Generated by Django 4.1.3 on 2023-05-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_alter_branch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('poid', models.IntegerField(db_column='POID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('po_status', models.IntegerField(blank=True, db_column='PO_Status', null=True)),
            ],
            options={
                'db_table': 'payment_option',
                'managed': True,
            },
        ),
    ]
