# Generated by Django 4.1.3 on 2023-05-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_paymentoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandtype',
            fields=[
                ('demand_type_id', models.IntegerField(db_column='Demand_Type_ID', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=100, null=True)),
                ('status_d', models.IntegerField(blank=True, db_column='Status_d', null=True)),
            ],
            options={
                'db_table': 'demandtype',
                'managed': True,
            },
        ),
    ]
