# Generated by Django 4.1.3 on 2023-06-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0004_demandtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandrate',
            fields=[
                ('drid', models.IntegerField(db_column='DRID', primary_key=True, serialize=False)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, db_column='Effective_Date', null=True)),
                ('iscurrent', models.IntegerField(blank=True, db_column='IsCurrent', null=True)),
                ('demand_type', models.ForeignKey(blank=True, db_column='Demand_type_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Department.demandtype')),
            ],
            options={
                'db_table': 'demandrate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('scno', models.IntegerField(blank=True, db_column='SCNO', null=True)),
                ('cusid', models.IntegerField(db_column='CUSID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, db_column='FullName', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('mobileno', models.IntegerField(blank=True, db_column='MobileNo', null=True)),
                ('branch', models.ForeignKey(blank=True, db_column='Branch_Id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Department.branch')),
                ('demand_type', models.ForeignKey(blank=True, db_column='Demand_type_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Department.demandtype')),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
    ]
