# Generated by Django 4.1.3 on 2023-06-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0006_bill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pid', models.IntegerField(db_column='PID', primary_key=True, serialize=False)),
                ('pdate', models.DateField(blank=True, db_column='PDate', null=True)),
                ('pamount', models.FloatField(blank=True, db_column='PAmount', null=True)),
                ('rebate_amt', models.FloatField(blank=True, db_column='Rebate_Amt', null=True)),
                ('fine_amt', models.FloatField(blank=True, db_column='Fine_Amt', null=True)),
                ('bid', models.ForeignKey(blank=True, db_column='BId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Department.bill')),
                ('payment_type', models.ForeignKey(blank=True, db_column='Payment_Type_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Department.paymentoption')),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
    ]
